title: JSON Editor
tagline: A powerful JSON editor component for React
description: A powerful JSON editor component with schema validation, path highlighting, and theme support.
baseurl: /jsoneditor
repository: bagaking/jsoneditor
url: https://bagaking.github.io

# SEO 设置
lang: zh-CN  # 设置语言
author:
  name: bagaking
  url: https://github.com/bagaking
twitter:
  username: bagaking
  card: summary
social:
  name: JSON Editor
  links:
    - https://github.com/bagaking/jsoneditor
    - https://www.npmjs.com/package/@bagaking/jsoneditor

# Open Graph 设置
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/jsoneditor-social-preview.png
      
# 主题设置
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Just the Docs 配置
color_scheme: light
search_enabled: true
heading_anchors: true
aux_links:
  "GitHub":
    - "https://github.com/bagaking/jsoneditor"
aux_links_new_tab: true
nav_external_links:
  - title: JSON Editor on GitHub
    url: https://github.com/bagaking/jsoneditor
    hide_icon: false

# 搜索配置
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# 其他设置
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .git
  - .gitignore
  - .github 