title: JSON Editor
description: A powerful JSON editor component with schema validation, path highlighting, and theme support.
baseurl: /jsoneditor
repository: bagaking/jsoneditor

# 主题设置
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Just the Docs 配置
color_scheme: light
search_enabled: true
heading_anchors: true
aux_links:
  "GitHub":
    - "https://github.com/bagaking/jsoneditor"
aux_links_new_tab: true
nav_external_links:
  - title: JSON Editor on GitHub
    url: https://github.com/bagaking/jsoneditor
    hide_icon: false

# 导航配置
nav:
  - title: JSON Editor
    url: /index
    nav_order: 1
  - title: 快速开始
    url: /guide/getting-started
    nav_order: 2
  - title: 基础用法
    url: /guide/basic-usage
    nav_order: 3
  - title: 使用方法
    nav_order: 4
    children:
      - title: 编辑器 API
        url: /api/editor
        nav_order: 1
      - title: 工具栏配置
        url: /api/toolbar
        nav_order: 2
      - title: 状态栏配置
        url: /api/statusbar
        nav_order: 3
      - title: Schema 面板配置
        url: /api/schema-panel
        nav_order: 4
      - title: Schema 验证
        url: /api/schema-validation
        nav_order: 5
      - title: 装饰系统
        url: /api/decoration
        nav_order: 6
      - title: 定制化指南
        url: /api/customization
        nav_order: 7
      - title: 直接操作编辑器核心 API
        url: /api/editor-core
        nav_order: 8
      - title: API 参考
        url: /api/editor-core
        nav_order: 8
  - title: 架构设计
    url: /design/architecture
    nav_order: 5
  - title: 术语表
    url: /design/glossary
    nav_order: 6

# 搜索配置
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# 其他设置
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .git
  - .gitignore
  - .github 